// GENERATED by scripts/make-defaults.mjs — do not edit by hand.

export interface DefaultImage {
  filename: string;
  url: string;
  id: string;
  category: string;
}

export const DEFAULT_IMAGES: DefaultImage[] = [
  {
    "filename": "default_blood_pressure_monitor.png",
    "url": "/uploads/default_blood_pressure_monitor.png",
    "id": "bp-101",
    "category": "blood_test"
  },
  {
    "filename": "default_hemoglobin_meter.png",
    "url": "/uploads/default_hemoglobin_meter.png",
    "id": "hem-201",
    "category": "blood_test"
  },
  {
    "filename": "default_glucometer.png",
    "url": "/uploads/default_glucometer.png",
    "id": "sugar-301",
    "category": "blood_test"
  },
  {
    "filename": "default_elastic_bandage.png",
    "url": "/uploads/default_elastic_bandage.png",
    "id": "band-401",
    "category": "bandage"
  },
  {
    "filename": "default_adhesive_bandage_pack.png",
    "url": "/uploads/default_adhesive_bandage_pack.png",
    "id": "band-402",
    "category": "bandage"
  },
  {
    "filename": "default_sterile_gauze.png",
    "url": "/uploads/default_sterile_gauze.png",
    "id": "gauze-501",
    "category": "gauze"
  },
  {
    "filename": "default_vitamin_c_1000.png",
    "url": "/uploads/default_vitamin_c_1000.png",
    "id": "vit-601",
    "category": "vitamin"
  },
  {
    "filename": "default_iron_supplement.png",
    "url": "/uploads/default_iron_supplement.png",
    "id": "vit-602",
    "category": "vitamin"
  },
  {
    "filename": "default_first_aid_kit.png",
    "url": "/uploads/default_first_aid_kit.png",
    "id": "aid-701",
    "category": "first_aid"
  },
  {
    "filename": "default_antiseptic_liquid.png",
    "url": "/uploads/default_antiseptic_liquid.png",
    "id": "ant-801",
    "category": "antiseptic"
  },
  {
    "filename": "default_iodine_solution.png",
    "url": "/uploads/default_iodine_solution.png",
    "id": "ant-802",
    "category": "antiseptic"
  },
  {
    "filename": "default_digital_thermometer.png",
    "url": "/uploads/default_digital_thermometer.png",
    "id": "therm-901",
    "category": "thermometer"
  },
  {
    "filename": "default_oxygen_cylinder_small.png",
    "url": "/uploads/default_oxygen_cylinder_small.png",
    "id": "oxy-1001",
    "category": "oxygen"
  },
  {
    "filename": "default_oxygen_mask.png",
    "url": "/uploads/default_oxygen_mask.png",
    "id": "oxy-1002",
    "category": "oxygen"
  }
];

export function defaultImageForId(id: string): string | null {
  const d = DEFAULT_IMAGES.find((x) => x.id === id);
  return d ? d.url : null;
}

export function defaultImageForCategory(category: string | null): string | null {
  const d = DEFAULT_IMAGES.find((x) => x.category === category);
  return d ? d.url : null;
}
