/**
 * Seed catalogue for the shop. Image filenames must exist in uploads/
 * (generated by `npm run make-defaults`).
 */
export interface SeedProduct {
  id: string;
  slug: string;
  name: string;
  price: number;
  stock: number;
  category: string;
  description: string;
  image_file: string;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "bp-101",
    slug: "blood_pressure_monitor",
    name: "Blood Pressure Monitor",
    price: 3200,
    stock: 50,
    category: "Equipment",
    description: "Automatic upper-arm blood pressure monitor with 99-reading memory and irregular heartbeat detection.",
    image_file: "default_blood_pressure_monitor.png",
  },
  {
    id: "hem-201",
    slug: "hemoglobin_meter",
    name: "Hemoglobin Meter",
    price: 4500,
    stock: 20,
    category: "Equipment",
    description: "Portable hemoglobin meter for point-of-care screening. Results in 60 seconds, includes 50 test cassettes.",
    image_file: "default_hemoglobin_meter.png",
  },
  {
    id: "sugar-301",
    slug: "glucometer",
    name: "Blood Glucose Meter",
    price: 1800,
    stock: 40,
    category: "Equipment",
    description: "Reliable glucose meter with 100 strips, lancets and a carrying case.",
    image_file: "default_glucometer.png",
  },
  {
    id: "band-401",
    slug: "elastic_bandage",
    name: "Elastic Bandage",
    price: 350,
    stock: 120,
    category: "Bandage",
    description: "High-elasticity crepe bandage, 10 cm × 4 m. Ideal for sprains and wound support.",
    image_file: "default_elastic_bandage.png",
  },
  {
    id: "band-402",
    slug: "adhesive_bandage_pack",
    name: "Adhesive Bandage Pack",
    price: 150,
    stock: 200,
    category: "Bandage",
    description: "100 assorted waterproof adhesive bandages for minor cuts and scrapes.",
    image_file: "default_adhesive_bandage_pack.png",
  },
  {
    id: "gauze-501",
    slug: "sterile_gauze",
    name: "Sterile Gauze Pads",
    price: 220,
    stock: 150,
    category: "Bandage",
    description: "Individually wrapped sterile gauze pads, 10 × 10 cm, box of 24.",
    image_file: "default_sterile_gauze.png",
  },
  {
    id: "vit-601",
    slug: "vitamin_c_1000",
    name: "Vitamin C 1000mg",
    price: 550,
    stock: 100,
    category: "Supplements",
    description: "1000 mg Vitamin C effervescent tablets, 20 count. Supports immune function.",
    image_file: "default_vitamin_c_1000.png",
  },
  {
    id: "vit-602",
    slug: "iron_supplement",
    name: "Iron Supplement",
    price: 780,
    stock: 90,
    category: "Supplements",
    description: "Ferrous sulfate + folic acid tablets, 30 count. For iron-deficiency support as advised by a doctor.",
    image_file: "default_iron_supplement.png",
  },
  {
    id: "aid-701",
    slug: "first_aid_kit",
    name: "First Aid Kit",
    price: 1250,
    stock: 35,
    category: "Healthcare",
    description: "Complete emergency first aid box with 50+ items: gauze, bandages, antiseptic, scissors, thermal blanket.",
    image_file: "default_first_aid_kit.png",
  },
  {
    id: "ant-801",
    slug: "antiseptic_liquid",
    name: "Antiseptic Liquid 250ml",
    price: 420,
    stock: 80,
    category: "Antiseptic",
    description: "Chlorhexidine-based antiseptic solution for wound cleansing, 250 ml bottle.",
    image_file: "default_antiseptic_liquid.png",
  },
  {
    id: "ant-802",
    slug: "iodine_solution",
    name: "Iodine Solution",
    price: 320,
    stock: 75,
    category: "Antiseptic",
    description: "Povidone-iodine 10% solution for external use, 100 ml with dropper.",
    image_file: "default_iodine_solution.png",
  },
  {
    id: "therm-901",
    slug: "digital_thermometer",
    name: "Digital Thermometer",
    price: 450,
    stock: 60,
    category: "Equipment",
    description: "Fast-read digital thermometer (10 s), oral/axillary, single use probe covers included.",
    image_file: "default_digital_thermometer.png",
  },
  {
    id: "oxy-1001",
    slug: "oxygen_cylinder_small",
    name: "Portable Oxygen Cylinder",
    price: 8500,
    stock: 8,
    category: "Oxygen",
    description: "Portable compressed oxygen cylinder (2 L) with regulator and mask — for prescribed use only.",
    image_file: "default_oxygen_cylinder_small.png",
  },
  {
    id: "oxy-1002",
    slug: "oxygen_mask",
    name: "Oxygen Mask Set",
    price: 650,
    stock: 45,
    category: "Oxygen",
    description: "Adult oxygen mask set with tubing and nose clips, hospital grade.",
    image_file: "default_oxygen_mask.png",
  },
];
